spring:
  application:
    name: gudocs
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gudocs
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
    show-sql: false

server:
  port: 8080