-- 소셜 로그인 전용 전환: users.email 의 UNIQUE 제약 제거용 1회성 스크립트.
--
-- 배경: 초기 스키마는 email 이 UNIQUE(@Column(unique=true)) 였다.
--       provider+providerId 식별로 바뀌면서 엔티티에서 unique 를 제거했지만,
--       ddl-auto: update 는 "이미 만들어진" UNIQUE 인덱스를 자동으로 삭제하지 않는다.
--       그래서 구 스키마로 한 번이라도 뜬 운영 DB에는 인덱스가 그대로 남아,
--       다른 제공자가 같은 이메일로 가입할 때 Duplicate entry 로 실패한다.
--
-- 사용법 (EC2 MySQL 에서 1회):
--   1) 실제 인덱스 이름 확인 (Hibernate 가 UK... 형태로 자동 생성했을 수 있음)
--        USE gudocs;
--        SHOW INDEX FROM users WHERE Column_name = 'email' AND Non_unique = 0;
--   2) 위에서 나온 Key_name 으로 아래 DROP 실행 (예시는 auto-gen 이름)
--        ALTER TABLE users DROP INDEX <실제_KEY_NAME>;
--
-- 신규로 새 DB에 배포한 경우(구 스키마 이력 없음)에는 인덱스 자체가 없으므로 실행 불필요.
